# Generated by Django 5.1.3 on 2025-03-03 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'WaitList Entries'},
        ),
    ]
