# Generated by Django 5.1.3 on 2025-04-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_waitlistentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ccp_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit Card'), ('ccp', 'CCP Edahabia')], default='card', max_length=10),
        ),
    ]
